# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ISS Position' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ISS Position
  pod 'Alamofire', '~> 4.7'

  target 'ISS PositionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ISS PositionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
